name = "Generall"
license = "MIT"
licenselink = "https://github.com/calintat/minimal/blob/master/LICENSE.md"
description = "Andrey's Personal blog theme"
homepage = "http://github.com/generall/minimal/"
tags = ["blog", "minimal", "personal", "responsive"]
features = ["responsive"]
min_version = "0.24.1"

[author]
  name = "Andrey Vasnetsov"
  homepage = "https://blog.vasnetsov.com/"
